name: beacon_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geocoding: ^4.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.17.0
  http: ^1.2.2
  intl: ^0.20.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  sentry_flutter: ^9.6.0
  shared_preferences: ^2.5.5
  sign_in_with_apple: ^7.0.1
  supabase_flutter: ^2.12.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/beacon-logo.png
    - assets/app_icon_final.jpg
    - assets/tiny_icon.png
    - assets/map_styles/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_final.jpg"
